channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - numpy=1.22.4
  - pandas=1.4.2
  - scipy=1.8.1
  - xarray=2022.3.0
  - geocube=0.3.1
  - geopandas=0.10.2
  - pyyaml=6.0
  - gstools=1.3.5
  - numba=0.53.1
  - jupyterlab=3.4.2
  - bokeh=2.4.3
  - jupyter_bokeh=3.0.4
  - qgrid=1.3.1
  - pip=22.1.2
  - pip:
    - -e .
